round1_feb2015: 
  description: Round 1, February 2015

  # condition definitions (multiple)
  conditions:
    - name: positive
      start_values: FUNC_POSITIVE(100,[1,100]) # 10 values between 1 and 10 (inclusive)
      target_values: FUNC_POSITIVE(100,[1,100])

    - name: negative
      start_values: FUNC_NEGATIVE(100,[1,100])
      target_values: FUNC_NEGATIVE(100,[1,100])

    - name: nonlinear
      start_values: FUNC_NONLINEAR(100,[1,100])
      target_values: FUNC_NONLINEAR(100,[1,100])

    - name: random
      start_values: FUNC_RANDOM(100,[1,100])
      target_values: FUNC_RANDOM(100,[1,100])

  chains_per_condition: 2   # Number of chains per condition
  generations_per_chain: 3  # Number of generation per chain
  tasks_per_generation: 3   # Number of tasks per generation
  percent_test_for_training: 50 # percent of values to use for training (chosen randomly)


  # Mechanical Turk Settings
  # - ignored if: is_mturk = false 
  is_mturk: false
  mturk_sandbox: true
  mturk_title: This is a test
  mturk_description: etc etc etc
  mturk_keywords: iterative learning
  mturk_award: 0.01
  mturk_duration: 3600 # one hour for HIT to to be completed
  mturk_lifetime: 31536000 # one year until HIT expires
  mturk_qualifications: "" # not used


  # Options for experiment interface
  #
  frontend_config:
    intro_help_text: |
    intro_help_text: |
      <p>
        <h4>In this experiment, we simply want to measure your ability to learn the 
        relationship between the lengths of two different lines.</h4>
        There are two stages: a Training Phase, and a Testing Phase.
      </p>

      <p>
        In the Training Phase, you will see:
        <ul>
          <li>one horizontal bar, across the top of the screen, partly filled in blue</li>
          <li>one vertical bar, along the right-hand side of the screen, empty</li>
          <li>a slider next to the vertical bar</li>
        </ul>
        like this:
      </p>
      <p>
        <img src="/images/fig1.png" class="col-md-12 well"/>
      </p>
      <p>
        Any % of the horizontal bar, from 1% to 100%, can be filled in blue.
        In the figure above, approximately 80% is filled in blue.
      </p>
      <p>
        You must drag the slider next to the vertical bar, on the right.
        As you do, that bar will fill with red.
      </p>
      <p>
        For each amount of blue in the horizontal bar, there is a correct amount of red
        in the vertical bar. At the beginning of the experiment, you will not know what
        the correct amounts are, so you must guess. Drag the slider to any part of the
        vertical bar. Like this:
      </p>
      <p>
        <img src="/images/fig2.png" class="col-md-12 well"/>
      </p>
      <p>
        When you have done this, click ‘Next’. After you have clicked ‘Next’,
        another vertical bar will appear, partly filled in yellow. This indicates
        the correct amount of the vertical bar that should be filled in, given the
        amount of the horizontal bar that is filled in. Like this:
      </p>
      <p>
        <img src="/images/fig3.png" class="col-md-12 well"/>
      </p>
      <p>
        If it was incorrect (as in the image above), the word ‘Incorrect’ will appear
        on the screen. You must now drag the slider to the same level as the yellow
        bar (or close to it). You can then click ‘Next’ to move on to the next round.
        If your guess was correct, or close to correct, the word ‘Correct!’ will appear
        on the screen. You can now click ‘Next’, and move on to the next round.
      </p>
      <p>
        There are 50 rounds in the Training Phase, each with a different amount of
        the blue bar filled in. For each amount of blue that is filled, you should
        try to remember how much of the red bar should be filled.
      </p>
      <p>
        Once you have completed the Training Phase, you will move on to the Testing Phase.
      </p>
      <p>
        The Testing Phase is the same as the Training Phase, except that here there is
        no feedback. In other words, there will be no yellow bar, and no noises.
        Instead, after you click ‘Next’, you will move straight on to the next round.
        You will not be told if you were correct or not.
      </p>
      <p>
        There are 100 rounds in the Testing Phase.
      </p>
      <p>
        Once you have completed the Testing Phase, click ‘Submit’ to complete the experiment. 
      </p>
      <p>
        <b>Many thanks.</b>
      </p>

    next_button_help_text: Adjust the vertical slider and click Next
    training_correct_text: <b>Correct!</b>
    training_wrong_text: <b>Incorrect.</b><br/>Adjust the slider to the correct value (indicated by the yellow bar) and click Next
    testing_help_text: |
      You have now completed the Training Phase. You will now move on to the Testing Phase. Here, there will be no yellow bar, and no feedback. You must decide for yourself what height to set the slider, based on what you learned in the Training Phase.
    final_help_text: |
      Thank you for taking part. 
