round1_feb2015: 
  description: Round 1, February 2015

  # condition definitions (multiple)
  conditions:
    - name: positive
      start_values: FUNC_POSITIVE(10,[1,10]) # 10 values between 1 and 10 (inclusive)
      target_values: FUNC_POSITIVE(10,[1,10])

    - name: negative
      start_values: FUNC_NEGATIVE(10,[1,10])
      target_values: FUNC_NEGATIVE(10,[1,10])

    - name: nonlinear
      start_values: FUNC_NONLINEAR(10,[1,10])
      target_values: FUNC_NONLINEAR(10,[1,10])

    - name: random
      start_values: FUNC_RANDOM(10,[1,10])
      target_values: FUNC_RANDOM(10,[1,10])

  chains_per_condition: 2   # Number of chains per condition
  generations_per_chain: 3  # Number of generation per chain
  tasks_per_generation: 3   # Number of tasks per generation
  percent_test_for_training: 50 # percent of values to use for training (chosen randomly)


  # Mechanical Turk Settings
  # - ignored if: is_mturk = false 
  is_mturk: false
  mturk_sandbox: true
  mturk_title: This is a test
  mturk_description: etc etc etc
  mturk_keywords: iterative learning
  mturk_award: 0.01
  mturk_duration: 3600 # one hour for HIT to to be completed
  mturk_lifetime: 31536000 # one year until HIT expires
  mturk_qualifications: "" # not used


  # Options for experiment interface
  #
  frontend_config:
    intro_help_text: |
    intro_help_text: |
      <p>
        In this experiment, we simply want to measure your ability to learn the 
        relationship between the lengths of two different lines. 
        There are two stages: a Training Phase, and a Testing Phase.
      </p>

      <p>
        In the Training Phase, you will see &#58;
        <ul>
          <li>one horizontal bar, across the top of the screen, partly filled in blue</li>
          <li>one vertical bar, along the right-hand side of the screen, empty</li>
          <li>a slider next to the vertical bar</li>
        </ul>
        like this:
        <img src="/images/fig1.png"/>
      </p>



    next_button_help_text: Adjust the vertical slider and click Next
    training_correct_text: <b>Correct!</b>
    training_wrong_text: <b>Incorrect.</b><br/>Adjust the slider to the correct value (indicated by the yellow bar) and click Next
    testing_help_text: |
      You have now completed the Training Phase. You will now move on to the Testing Phase. Here, there will be no yellow bar, and no feedback. You must decide for yourself what height to set the slider, based on what you learned in the Training Phase.
    final_help_text: |
      Thank you for taking part. 
