environment: production # <-- use this to set the environment
secret: CHANGME
alert_email: sr.erickson@gmail.com
# Environment-specific settings

production:
  base_url: https://il.thebig.computer
  database:
    adapter: sqlite3
    database: experiment_data_production.db

development:
  base_url: https://localhost:3000
  database:
    adapter: sqlite3
    database: experiment_data_development.db

test:
  base_url: https://localhost:3000
  database:
    adapter: sqlite3
    database: experiment_data_test.db